### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by superDross** [romainl/the-patient-vimmer#8]
I was wondering whether this project has been abandoned? I read the first couple of chapters and got quite excited at the prospect of reading a full version. However, I see there has been no new commits in around 4 years.

**Comment by romainl** [comment]
Hello @superDross. Yes, I can't say if the situation is temporary or definitive, but I've pretty much abandoned this project for several reasons.

One is basically that The Patient Vimmer is not much more than a subjective/opinionated rehashing of the user manual. As such, I believe it doesn't provide enough value over the base material to justify the necessary level of implication.

Another one is that I'm not happy with the overall design and pacing. I think it would need a good rethinking.

Another one is that the Vim ecosystem doesn't really suffer from a lack of extensive tutorials and publishing a new one wouldn't solve any actual problem. So, again, the cost doesn't seem justified.

Another one is that the nature of my work has changed in the last four years and I've had a lot less time and brain capacity for such a project. "Sadly" (quotes because I'm very happy with the way my career is going) It doesn't look like it will get better in the foreseeable feature.

Another one is that I now have another [somewhat related project](https://vimways.org/) that, in my opinion, has more chances of tipping the scales.

**Comment by superDross** [comment]
Thanks for the quick reply. That is a shame, I quite enjoyed the writing style and brevity. A sort of straight to the point approach with a little dry humour thrown in for good measure. Vimways is a nice resource, thank you. The 3rd article being of particular interest.

**Comment by jungle-boogie** [comment]
Congrats on your new life to keep you busy.
